package edu.sinchuk.kurs.views;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener;
import com.vaadin.server.VaadinSession;
import com.vaadin.ui.Label;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Button;
import edu.sinchuk.kurs.controllers.queries.OrderQuery;
import edu.sinchuk.kurs.models.entities.OrderEntity;
import edu.sinchuk.kurs.models.entities.UserEntity;
import edu.sinchuk.kurs.models.services.DataBaseConnection;
import edu.sinchuk.kurs.views.components.OrderComponent;
import edu.sinchuk.kurs.views.components.OrdersHeaderComponent;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainView extends VerticalLayout implements View {

    final static public String NAME = "main";

    private static final Logger logger = Logger.getLogger("MainView");

    protected VerticalLayout orders;
    protected Button myOrders;
    protected Button allOrders;

    public MainView() {
        addComponent(new OrdersHeaderComponent());
        Design.read(this);

        UserEntity userEntity = (UserEntity) VaadinSession.getCurrent().getAttribute("user");

        Button titles = new Button("titles");
        titles.addClickListener(new Button.ClickListener() {
            @Override
            public void buttonClick(Button.ClickEvent clickEvent) {
                DataBaseConnection connection = new DataBaseConnection();
                try {
                    OrderQuery orderQuery = new OrderQuery(connection.connect());
                    List<String> ordersTitles = orderQuery.selectAllTitles();
                    ordersTitles.forEach(orderTitles -> {
                        System.out.println(orderTitles);
                    });
                } catch (ClassNotFoundException e) {
                    addComponent(new Label("Ошибка соединения с базой!!!"));
                } catch (SQLException e) {
                    addComponent(new Label("Ошибка запроса к базе!!!"));
                }
            }
        });

        addComponent(titles);

        DataBaseConnection connection = new DataBaseConnection();
        try {
            OrderQuery orderQuery = new OrderQuery(connection.connect());
            List<OrderEntity> ordersEntities = orderQuery.selectAll();
            ordersEntities.forEach(orderEntity -> {
                orders.addComponent(new OrderComponent(orderEntity));
            });
        } catch (ClassNotFoundException e) {
            addComponent(new Label("Ошибка соединения с базой!!!"));
        } catch (SQLException e) {
            addComponent(new Label("Ошибка запроса к базе!!!"));
        }

        myOrders.addClickListener(new Button.ClickListener() {
            @Override
            public void buttonClick(Button.ClickEvent clickEvent) {
                DataBaseConnection connection = new DataBaseConnection();
                try {
                    OrderQuery orderQuery = new OrderQuery(connection.connect());
                    List<OrderEntity> ordersEntities = new ArrayList<OrderEntity>();
                    if (userEntity.getFkGroupId() == 1) {
                        ordersEntities = orderQuery.selectByCreator(userEntity.getUserId());
                    } else if (userEntity.getFkGroupId() == 2) {
                        ordersEntities = orderQuery.selectByDeveloper(userEntity.getUserId());
                    }
                    orders.removeAllComponents();
                    ordersEntities.forEach(orderEntity -> {
                        orders.addComponent(new OrderComponent(orderEntity));
                    });
                } catch (ClassNotFoundException e) {
                    addComponent(new Label("Ошибка соединения с базой!!!"));
                } catch (SQLException e) {
                    addComponent(new Label("Ошибка запроса к базе!!!"));
                }
            }
        });

        allOrders.addClickListener(new Button.ClickListener() {
            @Override
            public void buttonClick(Button.ClickEvent clickEvent) {
                DataBaseConnection connection = new DataBaseConnection();
                try {
                    OrderQuery orderQuery = new OrderQuery(connection.connect());
                    List<OrderEntity> ordersEntities = orderQuery.selectAll();
                    orders.removeAllComponents();
                    ordersEntities.forEach(orderEntity -> {
                        orders.addComponent(new OrderComponent(orderEntity));
                    });
                } catch (ClassNotFoundException e) {
                    addComponent(new Label("Ошибка соединения с базой!!!"));
                } catch (SQLException e) {
                    addComponent(new Label("Ошибка запроса к базе!!!"));
                }
            }
        });
    }

    @Override
    public void enter(ViewChangeListener.ViewChangeEvent viewChangeEvent) {
    }
}
