package edu.sinchuk.kurs.views.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Button;
import edu.sinchuk.kurs.controllers.queries.OrderQuery;
import edu.sinchuk.kurs.controllers.queries.UserQuery;
import edu.sinchuk.kurs.models.entities.OrderEntity;
import edu.sinchuk.kurs.models.entities.UserEntity;
import edu.sinchuk.kurs.models.services.DataBaseConnection;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class UserComponent extends VerticalLayout {
    protected Label login;
    protected Label pass;
    protected Label group;
    protected Button delete;

    private UserEntity user;

    public UserComponent(UserEntity user) {
        Design.read(this);

        this.user = user;

        login.setValue("Login: " + user.getUserLogin());
        pass.setValue("Password: " + user.getUserPassword());
        if (user.getFkGroupId() == 1) {
            group.setValue("Group: Customer");
        } else if (user.getFkGroupId() == 2) {
            group.setValue("Group: Developer");
        }

        delete.addClickListener(new Button.ClickListener() {
            @Override
            public void buttonClick(Button.ClickEvent clickEvent) {
                DataBaseConnection connection = new DataBaseConnection();
                Connection conn = null;
                try {
                    conn = connection.connect();
                    conn.setAutoCommit(false);
                    UserQuery userQuery = new UserQuery(conn);
                    userQuery.deleteUserWithTransation(user.getUserId(),user.getFkGroupId());
                    removeAllComponents();
                } catch (ClassNotFoundException e) {
                    addComponent(new Label("Ошибка соединения с базой!!!"));
                } catch (SQLException e) {
                    addComponent(new Label("Ошибка удаления!!!"));
                }
            }
        });
    }
}
